# This is a basic action to list annotations

name: List Annotations

on: workflow_dispatch

jobs:

  list-annotations:
    runs-on: ubuntu-latest
    env:
      ACCEPT: application/vnd.github+json
      AUTHORIZATION: token ${{ secrets.GITHUB_TOKEN }}

    steps:

    # Query the workflows for the current repository
    - name: Query workflows
      uses: octokit/request-action@v2
      with:
        route: GET /repos/${{ env.GITHUB_REPOSITORY }}/actions/workflows
        headers: |
          Accept: ${{ env.ACCEPT }}
          Authorization: ${{ env.AUTHORIZATION }}
      id: workflows
    
    # Loop through the workflows and fetch the jobs for each workflow
    - name: Fetch jobs for each workflow
      uses: octokit/request-action@v2
      id: jobs
      with:
        route: GET /repos/${{ env.GITHUB_REPOSITORY }}/actions/runs
        params: |
          workflow_id: ${{ jobs.id }}
        headers: |
          Accept: ${{ env.ACCEPT }}
          Authorization: ${{ env.AUTHORIZATION }}
        forEach: ${{ steps.workflows.data }}
    
    # List the annotations for each check run
    - name: List annotations for each check run
      uses: octokit/request-action@v2
      id: annotations
      with:
        route: GET ${{ jobs.check_run_url }}/annotations
        headers: |
          Accept: ${{ env.ACCEPT }}
          Authorization: ${{ env.AUTHORIZATION }}
        forEach: ${{ steps.jobs.data.jobs }}
    
