# This is a basic action to run a bash script that will list annotations

name: List Annotations

on: workflow_dispatch

jobs:

  list-annotations:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3


      - name: set executable permissions for the script
        run: chmod +x list-annotations.sh

          
      - name: run the list annotations script
        run: |
          chmod +x list-annotations.sh
          ./list-annotations.sh
